language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - hhvm

install:
    - wget http://getcomposer.org/composer.phar
    - /usr/bin/php -d memory_limit=2g ./composer.phar install

script: vendor/bin/phpunit
