language: php
php:
  - 7.1
  - 7.0
  - 5.6

install:
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install

script: vendor/bin/phpunit
