services:
    kernel.listener.symfony1_fallback:
        class: Hostnet\HnDependencyInjectionPlugin\Symfony1Fallback
        arguments: [@kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    kernel.listener.cache_warmer:
        class: Hostnet\HnDependencyInjectionPlugin\CacheWarmer
        arguments: [@kernel]
        tags:
            - { name: kernel.cache_warmer }