services:
    kernel.listener.symfony1_fallback:
        class: Hostnet\HnDependencyInjectionPlugin\Symfony1Fallback
        arguments: [@kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
